### PR TITLE
fix: clear wallet context on disconnect

### LINKED ISSUE #113: Reset context when disconnecting/lock wallet
Severity: low | Priority: low

**Note**: After connecting Metamask wallet, and setting everything ready for a transfer, if the user disconnects the wallet via disconnect or lock ( metamask option), the context is not reseted. 

image

### PR DESCRIPTION
**Pull request by Lykhoyda**
Closes #113

The original issue, mentions NOT clear the selected and destination network. But we fetch the resource data and other data on selecting the destination network, so to avoid unclear behavior for the user to click again the destination network I clear all the data. If it's important to have the behavior to keep the state of networks, it would be better to keep at least a selected network and a clear destination network to avoid potential bugs with the data being not updated on component levels. IMO clearing the entire state is the most bulletproof way to avoid previous selected data

### CODE REVIEW

File: packages/widget/src/components/resource-amount-selector/resource-amount-selector.ts [hunk 1]
```diff
@@ -43,6 +41,16 @@ export class AmountSelector extends BaseComponent {
   @state() validationMessage: string | null = null;
   @state() amount: string = '0';
 
+  constructor() {
+    super();
+    document.addEventListener('wallet-disconnected', () => {
```
Comment (mpetrunic) [inline packages/widget/src/components/resource-amount-selector/resource-amount-selector.ts:46]: instead of doing this everywhere, can you move this logic into transferController?

File: packages/widget/src/controllers/wallet-manager/manager.ts [hunk 2]
```diff
@@ -61,6 +61,9 @@ export class WalletController implements ReactiveController {
   disconnectWallet = (): void => {
     this.disconnectEvmWallet();
     this.disconnectSubstrateWallet();
+    this.host.dispatchEvent(
```
Comment (mpetrunic) [inline packages/widget/src/controllers/wallet-manager/manager.ts:64]: Don't think you need this. TransferController is subscribed to walletContext changes https://github.com/sygmaprotocol/sygma-widget/blob/dev/packages/widget/src/controllers/transfers/fungible-token-transfer.ts#L71

so you can check is wallet is disconnected on every change

**Review by mpetrunic — CHANGES_REQUESTED** [review]

File: packages/widget/src/components/resource-amount-selector/resource-amount-selector.ts (hunk 1 above)
Comment (Lykhoyda) [reply packages/widget/src/components/resource-amount-selector/resource-amount-selector.ts]: good idea! I tried this approach but from the first try it didn't go well :) Please check the updated code

**Comment by mpetrunic** [comment]
This doesn't resolve #133. Please open new PR to address the issue.Right now if I start new transfer, source network is resetted while wallet remains connected

**Review by mpetrunic — APPROVED** [review]
